services:
  postgres:
    image: "postgres:16.3"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data

  # migrator:
  #   build:
  #     context: .
  #     dockerfile: ./apps/server/Dockerfile.migrator
  #   depends_on:
  #     - postgres
  #   environment:
  #     - POSTGRES_URL=${POSTGRES_URL}

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/server/Dockerfile.server
  #   depends_on:
  #     migrator:
  #       condition: service_completed_successfully
  #   restart: always
  #   environment:
  #     - POSTGRES_URL=${POSTGRES_URL}
  #     - SECRET_TOKEN=${SECRET_TOKEN}
  #     - ADMIN_NAME=${ADMIN_NAME}
  #   ports:
  #     - 6732:8080

  cms-migrate:
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile.cms
      target: builder
    depends_on:
      - postgres
    working_dir: /app
    environment:
      DATABASE_URL: ${CMS_DATABASE_URL}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    command: sh -c "corepack enable pnpm && pnpm payload migrate"

  cms:
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile.cms
    depends_on:
      - postgres
      - cms-migrate
    restart: always
    environment:
      DATABASE_URL: ${CMS_DATABASE_URL}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ports:
      - 3232:3000

  website:
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile.website
      args:
        - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
        - NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
        - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
        - NEXT_PUBLIC_GA_CONVERSION_ID=${NEXT_PUBLIC_GA_CONVERSION_ID}
        - CMS_URL=http://cms:3000
        - RESEND_API_KEY=${RESEND_API_KEY}
        - NEXT_PUBLIC_HOST_URL=${NEXT_PUBLIC_HOST_URL}
    depends_on:
      - cms
    restart: always
    environment:
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
      - NEXT_PUBLIC_GA_CONVERSION_ID=${NEXT_PUBLIC_GA_CONVERSION_ID}
      - CMS_URL=http://cms:3000
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NEXT_PUBLIC_HOST_URL=${NEXT_PUBLIC_HOST_URL}
    ports:
      - 3000:3000

volumes:
  dbdata:
