FROM node:18-alpine
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app
COPY ./apps/server/. .
RUN pnpm i --frozen-lockfile
RUN pnpm run build
EXPOSE 8080
CMD pnpm start
