FROM node:18-alpine
WORKDIR /app
ARG NEXT_PUBLIC_SERVER_URL
ENV NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
COPY package*.json ./
COPY ./apps/website/. .
RUN npm ci
RUN npm run build
EXPOSE 3000
CMD npm start
